name: Build

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Lint
      run:  ./gradlew lintDebug

    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
